In [3]:
import torch
import numpy as np

## part1 creating tensors

In [18]:
# 1. 根据已有的数据创建张量（tensor）
def test01():

    # 1.1 创建标量
    data = torch.tensor(10)
    print(data)
    # 1.2 使用numpy array来创建
    data = np.random.randn(2,3)
    data = torch.tensor(data)
    print(data)
    # 1.3 使用list来创建
    data = [[10., 20., 30.],[20., 20., 30.]]
    data = torch.tensor(data)
    print(data)

# 2. 创建指定形状的张量
def test02():

    # 2.1 2行 3列
    data = torch.Tensor(2,3) #制定形状用大写T
    print(data)

    # 2.2 创建制定值
    # 传递列表
    data = torch.Tensor([2,3])
    print(data)

# 3. 创建指定类型的张量
def test03():
    # int32 类型
    data = torch.IntTensor(2,3)
    print(data)

    #torch.ShortTensor(2,3) # int16 类型
    #torch.LongTensor(2,3) # int32 类型
    #torch.FloatTensor(2,3) # float32 类型

    #如果创建指定类型的张量与传递类型不匹配，会发生类型转换


In [19]:
if __name__ == '__main__':
    test03()

tensor([[1388512288,        699,          0],
        [         0,          0,          0]], dtype=torch.int32)


## part2 creating specific tensors

In [ ]:
# functions
# 1. torch.arange && torch.linspace
# 2. torch.randominit_seed && torch.manual_seed
# 3. torch.randn

In [4]:
# 1. 创建线性空间的张量
def test01():
    # 1.1. 在指定区间按照步长生成元素[srat, end, step)
    data = torch.arange(0, 10, 2)
    print(data)
    
    # 1.2. 在指定区间指定元素个数[srat, end, number)
    data = torch.linspace(0, 10, 1000)
    print(data)
# 2. 创建随机张量
def test02():
    # 固定随机数种子
    torch.manual_seed(10)
    # 2.1 创建随机张量
    data = torch.randn(2, 2,3) #number of matrices, row, col
    print(data)
    # 2.2 固定随机数
    print("random seed:", torch.random.initial_seed())


In [5]:
if __name__ == '__main__':
    test02()

tensor([[[-0.6014, -1.0122, -0.3023],
         [-1.2277,  0.9198, -0.3485]],

        [[-0.8692, -0.9582, -1.1920],
         [ 1.9050, -0.9373, -0.8465]]])
random seed: 10


## part3 creating 0&1s tensors

In [ ]:
# functions
# 1. torch.ones && torch.ones_like
# 2. torch.zeros && torch.zeros_like
# 3. torch.full && torch.full_like

In [27]:
# 1. creating all 0s tensor
def test01():
    # 1.1 creating specific shape of all 0s tensor
    data = torch.zeros(2,3)
    print(data)
    # 1.2 according to other data's shape
    data = torch.zeros_like(data)
    print(data)
# 2. creating all 1s tensor
def test02():
    # 2.1 creating specific shape of all 1s tensor
    data = torch.ones(2,3)
    print(data)
    # 2.2 according to other data's shape
    data = torch.ones_like(data)
    print(data)
# 3. creating given value tensor
def test03():
    # 3.1 creating a (2,3) shape all 10s tensor (shape, value)
    data = torch.full([2,3], 10)
    print(data)
    # 3.2 creating a shape as same as the data and all 200s tensor
    data = torch.full_like(data, 200)
    print(data)

In [28]:
if __name__ == '__main__':
    test03()

tensor([[10, 10, 10],
        [10, 10, 10]])
tensor([[200, 200, 200],
        [200, 200, 200]])


# part4 get the type of tensors

In [ ]:
# functions
#1. tensor.type(torch.DouableTensor)
#2. torch.double()

In [36]:
# 1. type function
def test01():
    data = torch.full([2,3], 10)
    print(data.dtype)
    
    data = data.type(torch.DoubleTensor)
    print(data.dtype)
# 2. specific type function
def test02():
    data = torch.full([2,3], 10)
    print(data.dtype)

    data = data.double()
    print(data.dtype)




In [37]:
if __name__ == '__main__':
    test02()

torch.int64
torch.float64
