In [3]:
import torch
import numpy as np

# part1 basic calculation

In [4]:
# 1. non inplace calculation
def test01():
    data = torch.randint(0, 10, [2,3])
    print(data)
    data = data.add(10)
    print(data)
    
    # sub, mul, div, neg
# 2. inplace calculation
def test02():
    data = torch.randint(0, 10, [2,3])
    print(data)
    data.add_(10)
    print(data)

In [5]:
if __name__ == '__main__':
    test02()

tensor([[4, 6, 6],
        [5, 7, 0]])
tensor([[14, 16, 16],
        [15, 17, 10]])


# part2 Hadamard product

In [12]:
# 1. using mul
def test01():
    data1 = torch.tensor([[1,2], [3,4]])
    data2 = torch.tensor([[3,4], [5,6]])
    data = data1.mul(data2)
    print(data)
    
# 2. using '*'
def test02():
    data1 = torch.tensor([[1,2], [3,4]])
    data2 = torch.tensor([[3,4], [5,6]])
    data = data1*data2
    print(data)

In [13]:
if __name__ == '__main__':
    test01()
    test02()

tensor([[ 3,  8],
        [15, 24]])
tensor([[ 3,  8],
        [15, 24]])


# part3 dot product

In [30]:
# 1. using @ 
def test01():
    data1 = torch.tensor([[1,2], [3,4], [5,6]]) # 3*2
    data2 = torch.tensor([[3,4], [5,6]]) # 2*2
    data = data1@data2
    print(data)
# 2. using mm function
def test02():
    data1 = torch.tensor([[1,2], [3,4], [5,6]]) # 3*2
    data2 = torch.tensor([[3,4], [5,6]]) # 2*2
    data = torch.mm(data1,data2)
    print(data)
# 3. using bmm function # mm but for same number of multiple matrices in each tensor
def test03():
    data1 = torch.randn(3,4,5) 
    data2 = torch.randn(3,5,8) 
    data = torch.bmm(data1,data2)
    print(data.shape)
# 4. using matmul function # bmm+mm
def test04():
    data1 = torch.randn(4,5) 
    data2 = torch.randn(5,8) 
    print(torch.matmul(data1,data2).shape)
    data1 = torch.randn(3,4,5) 
    data2 = torch.randn(3,5,8) 
    print(torch.matmul(data1,data2).shape)
    data1 = torch.randn(3,4,5) 
    data2 = torch.randn(5,8) 
    print(torch.matmul(data1,data2).shape)

In [31]:
if __name__ == '__main__':
    test04()

torch.Size([4, 8])
torch.Size([3, 4, 8])
torch.Size([3, 4, 8])


# part4 set calculating device

In [ ]:
# 1. using cude
def test01():
    data = torch.tensor([10,20,30])
    print('device:', data.device)

    # moving to gpu
    data = data.cuda()
    print('device:', data.device)

    # moving tensor from gpu to cpu
    data = data.cpu()
    print('device:', data.device)
# 2. creating tensors on the gpu directly
def test02():
    data = torch.tensor([10,20,30], device = 'cuda:0')
    print('device:', data.device)
# 3. using to method
def test03(): 
    data = torch.tensor([10,20,30])
    print('device:', data.device)

    data = data.to('cuda:0')
    print('device:', data.device)
# 4. note: tensors storing on differnt devices can not directly do calculation
def test04(): 
    data1 = torch.tensor([10,20,30])
    data2 = torch.tensor([10,20,30], device = 'cuda:0')

    data = data1 + data2
    print(data)

In [23]:
if __name__ == '__main__':
    test04()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!