In [2]:
import torch
import numpy as np

# part1 tensor to numpy 

In [9]:
# 1. tensor to numpy list
def test01():
    data_tensor = torch.tensor([1, 2, 3])
    data_np = data_tensor.numpy()

    print(type(data_tensor))
    print(type(data_np))

# 2. tensor and numpy list sharing memory
def test02():
    data_tensor = torch.tensor([1, 2, 3])
    data_np = data_tensor.numpy()

    # change value of tensor will change the value of numpy list
    data_tensor[0] = 100

    print(data_tensor)
    print(data_np)

# 3. using copy function not sharing the memory
def test03():
    data_tensor = torch.tensor([1, 2, 3])
    data_np = data_tensor.numpy().copy()

    data_tensor[0] = 100

    print(data_tensor)
    print(data_np)


In [11]:
if __name__ == '__main__':
    test03()

tensor([100,   2,   3])
[1 2 3]


# part2 numpy to tensor

In [16]:
# 1. from_numpy function
def test01():
    data_np = np.array([2, 3, 4])
    data_tensor = torch.from_numpy(data_np) # directly change type
    print(type(data_np))
    print(type(data_tensor))

    # default sharing memory
    data_tensor[0] = 100

    print(data_np)
    print(data_tensor)
# 2. torch.tensor function
def test02():
    data_np = np.array([2, 3, 4])
    data_tensor = torch.tensor(data_np) # creating a copy of numpy array in tensor

    # change value of tensor will change the value of numpy list
    data_tensor[0] = 100

    print(data_tensor)
    print(data_np)


In [17]:
if __name__ == '__main__':
    test02()

tensor([100,   3,   4], dtype=torch.int32)
[2 3 4]


# part3 math tensor to number

In [22]:
def test():
    t1 = torch.tensor(30)
    t2 = torch.tensor([30])
    t3 = torch.tensor([[30]])

    print(t1.shape)
    print(t2.shape)
    print(t3.shape)

    # get value only # note: avaiable for only one number case
    print(t1.item()) 
    print(t2.item())
    print(t3.item())

    t4 = torch.tensor([[30,1]])
    print(t4.item())

In [23]:
if __name__ == '__main__':
    test()

torch.Size([])
torch.Size([1])
torch.Size([1, 1])
30
30
30


RuntimeError: a Tensor with 2 elements cannot be converted to Scalar