In [1]:
import torch

# 1. function torch.cat

In [16]:
def test():
    torch.manual_seed(10)
    data1 = torch.randint(0, 10, [3, 4, 5])
    data2 = torch.randint(0, 10, [3, 4, 5])

    print(data1.shape)
    print(data2.shape)

    # 1. concate using 0 dimension
    data_new = torch.cat([data1, data2], dim = 0)
    print(data_new.shape)

    # 2. using 1 dimension
    data_new = torch.cat([data1, data2], dim = 1)
    print(data_new.shape)

    # 2. using 2 dimension
    data_new = torch.cat([data1, data2], dim = 2)
    print(data_new.shape)

In [17]:
if __name__ == '__main__':
    test()

torch.Size([3, 4, 5])
torch.Size([3, 4, 5])
torch.Size([6, 4, 5])
torch.Size([3, 8, 5])
torch.Size([3, 4, 10])


# 2. function torch.stack

In [30]:
def test():
    torch.manual_seed(10)
    data1 = torch.randint(0, 10, [2,3])
    data2 = torch.randint(0, 10, [2,3])
    print(data1)
    print(data2)

    # 1. 0 dimension
    data_new = torch.stack([data1, data2], dim = 0) # whole single tensor
    print(data_new)

    # 2. 1 dimension
    data_new = torch.stack([data1, data2], dim = 1) # each row of single tensor
    print(data_new)

    # 3. 2 dimension
    data_new = torch.stack([data1, data2], dim = 2) # each column of single tensor
    print(data_new)


In [31]:
if __name__ == '__main__':
    test()

tensor([[7, 5, 2],
        [7, 2, 5]])
tensor([[7, 2, 1],
        [5, 6, 3]])
tensor([[[7, 5, 2],
         [7, 2, 5]],

        [[7, 2, 1],
         [5, 6, 3]]])
tensor([[[7, 5, 2],
         [7, 2, 1]],

        [[7, 2, 5],
         [5, 6, 3]]])
tensor([[[7, 7],
         [5, 2],
         [2, 1]],

        [[7, 5],
         [2, 6],
         [5, 3]]])
