In [3]:
import torch

# 1. row, col and list indexing

In [15]:
# 1. row col indexing
def test01():
    data = torch.randint(0, 10, [4,5])
    print(data)
    print('-'*30)

    # 1.1 get target row element
    print(data[0])
    # 1.2 get target col element
    print(data[:, 0])

# 2. list indexing
def test02():
    torch.manual_seed(10)

    data = torch.randint(0, 10, [4,5])
    print(data)
    print('-'*30)

    print(data[[0,2,3],[0,1,2]]) # get [0,0], [2,1], [3,2]
    print(data[[[0],[2],[3]],[0, 1, 2]]) # get 0, 1, 2 cols from 0, 2, 3 rows

In [16]:
if __name__ == '__main__':
    test02()

tensor([[7, 5, 2, 7, 2],
        [5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6],
        [3, 4, 0, 6, 2]])
------------------------------
tensor([7, 3, 0])
tensor([[7, 5, 2],
        [6, 3, 1],
        [3, 4, 0]])


# 2. bool indexing and mutlti dimention indexing

In [24]:
# 1. bool indexing
def test01():
    torch.manual_seed(10)
    data = torch.randint(0, 10, [4,5])
    print(data)
    print('-'*30)

    # values > 3 in tensor
    print(data > 3) # returning bool values
    print('-'*30)
    
    # 返回第二列元素大于6的行
    print(data[data[:, 1] > 6])
    print('-'*30)

    # 返回第二行大于3的所有列
    print(data[:,data[1] > 3])
    print('-'*30)

In [25]:
if __name__ == '__main__':
    test01()

tensor([[7, 5, 2, 7, 2],
        [5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6],
        [3, 4, 0, 6, 2]])
------------------------------
tensor([[ True,  True, False,  True, False],
        [ True,  True, False, False,  True],
        [ True, False, False, False,  True],
        [False,  True, False,  True, False]])
------------------------------
tensor([[5, 7, 2, 1, 5]])
------------------------------
tensor([[7, 5, 2],
        [5, 7, 5],
        [6, 3, 6],
        [3, 4, 2]])
------------------------------


In [30]:
# 2. multi dimension indexing
def test02():
    torch.manual_seed(10)

    data = torch.randint(0, 10, [3, 4, 5])
    print(data)
    print('-'*30)

    print(data[0, :, :])
    print('-'*30)

In [31]:
if __name__ == '__main__':
    test02()

tensor([[[7, 5, 2, 7, 2],
         [5, 7, 2, 1, 5],
         [6, 3, 1, 0, 6],
         [3, 4, 0, 6, 2]],

        [[8, 9, 2, 0, 9],
         [9, 4, 4, 9, 4],
         [4, 5, 4, 0, 8],
         [9, 3, 0, 9, 3]],

        [[7, 9, 5, 2, 9],
         [6, 6, 2, 8, 9],
         [6, 9, 1, 9, 2],
         [1, 2, 9, 7, 2]]])
------------------------------
tensor([[7, 5, 2, 7, 2],
        [5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6],
        [3, 4, 0, 6, 2]])
------------------------------
