In [1]:
import torch

# 1. reshape function

In [14]:
def test():
    torch.manual_seed(10)
    data = torch.randint(0, 10, [4, 5])
    print(data)
    print('-'*30)

    # searching tensor shape
    print(data.shape, data.shape[0], data.shape[1])
    print(data.size(), data.size(0), data.size(1))
    print('-'*30)

    # change tensor shape
    new_data = data.reshape(2,10) # number of elements need to be the same 
    print(new_data)
    # can autofilled using -1 
    new_data = data.reshape(2,-1) 
    print(new_data)

In [15]:
if __name__ == '__main__':
    test()

tensor([[7, 5, 2, 7, 2],
        [5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6],
        [3, 4, 0, 6, 2]])
------------------------------
torch.Size([4, 5]) 4 5
torch.Size([4, 5]) 4 5
------------------------------
tensor([[7, 5, 2, 7, 2, 5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6, 3, 4, 0, 6, 2]])
tensor([[7, 5, 2, 7, 2, 5, 7, 2, 1, 5],
        [6, 3, 1, 0, 6, 3, 4, 0, 6, 2]])


# 2. transpose and permute

In [20]:
# 2.1 transpose
def test01():
    torch.manual_seed(10)
    data = torch.randint(0, 10, [3, 4, 5])
    print(data)
    print('-'*30)

    # chagne to (4, 3, 5)
    # recalculate the matrix
    new_data = data.reshape(4, 3, 5)
    print(new_data.shape)

    # directly change values in two dimensions
    # note: only can switch two dimensions at one time
    new_data = torch.transpose(data, 0, 2)
    print(new_data.shape)


In [22]:
if __name__ == '__main__':
    test01()

tensor([[[7, 5, 2, 7, 2],
         [5, 7, 2, 1, 5],
         [6, 3, 1, 0, 6],
         [3, 4, 0, 6, 2]],

        [[8, 9, 2, 0, 9],
         [9, 4, 4, 9, 4],
         [4, 5, 4, 0, 8],
         [9, 3, 0, 9, 3]],

        [[7, 9, 5, 2, 9],
         [6, 6, 2, 8, 9],
         [6, 9, 1, 9, 2],
         [1, 2, 9, 7, 2]]])
------------------------------
torch.Size([4, 3, 5])
torch.Size([5, 4, 3])


In [25]:
# 2.2 permute
# switch multiple dimensions at one time
def test02():
    torch.manual_seed(10)
    data = torch.randint(0, 10, [3, 4, 5])
    
    new_data = torch.permute(data, [1, 2, 0])
    print(new_data.shape)
    print('-'*30)
    

In [26]:
if __name__ == '__main__':
    test02()

torch.Size([4, 5, 3])
------------------------------


# 3. view and contigous

In [47]:
# view function
def test01():
    data = torch.tensor([[10, 20, 30], [40, 50, 60]])
    data = data.view(3,2)
    print(data.shape)

    # is_contiguous: check tensor is continuous
    print(data.is_contiguous())

def test02():
    # note: after using transpose or permute functions, memory space is not contnuous
    data = torch.tensor([[10, 20, 30], [40, 50, 60]])
    print('是否连续:', data.is_contiguous())
    data = torch.transpose(data, 0, 1)
    print('是否连续:', data.is_contiguous())

    data = data.contiguous().view(2,3)
    print(data)

In [48]:
if __name__ == '__main__':
    test01()

torch.Size([3, 2])
True


In [56]:
def test02():
    # note: after using transpose or permute functions, memory space is not contnuous
    data = torch.tensor([[10, 20, 30], [40, 50, 60]])
    print(data)
    print('是否连续:', data.is_contiguous())
    data = torch.transpose(data, 0, 1)
    print(data)
    print('是否连续:', data.is_contiguous())

    data = data.contiguous().view(2,3)
    print(data)

In [57]:
if __name__ == '__main__':
    test02()

tensor([[10, 20, 30],
        [40, 50, 60]])
是否连续: True
tensor([[10, 40],
        [20, 50],
        [30, 60]])
是否连续: False
tensor([[10, 40, 20],
        [50, 30, 60]])


# 4. squeeze and unsqueeze

In [70]:
# 4.1 squeeze function
def test01():
    data = torch.randint(0, 10, [1, 3, 1, 5])
    print(data.shape)
    print(data)
    print('-'*30)

    # clear all dimension 1
    new_data = data.squeeze()
    print(new_data.shape)
    print(new_data)
    print('-'*30)

    # clear target dimension 1
    new_data = data.squeeze(2)
    print(new_data.shape)
    print(new_data)


In [71]:
if __name__ == '__main__':
    test01()

torch.Size([1, 3, 1, 5])
tensor([[[[8, 5, 9, 8, 3]],

         [[8, 4, 8, 6, 9]],

         [[5, 0, 4, 0, 3]]]])
------------------------------
torch.Size([3, 5])
tensor([[8, 5, 9, 8, 3],
        [8, 4, 8, 6, 9],
        [5, 0, 4, 0, 3]])
------------------------------
torch.Size([1, 3, 5])
tensor([[[8, 5, 9, 8, 3],
         [8, 4, 8, 6, 9],
         [5, 0, 4, 0, 3]]])


In [77]:
# 4.2 unsqueeze function
def test02():
    data = torch.randint(0, 10, [3, 5])
    print(data.shape)
    print(data)
    print('-'*30)

    # use unsqueeze to increase dimension
    new_data = data.unsqueeze(1)
    print(new_data.shape)
    print(new_data)
    print('-'*30)

    new_data = data.unsqueeze(-1)
    print(new_data.shape)
    print(new_data)
    print('-'*30)

In [78]:
if __name__ == '__main__':
    test02()

torch.Size([3, 5])
tensor([[5, 5, 7, 1, 5],
        [0, 0, 9, 1, 0],
        [9, 9, 9, 4, 9]])
------------------------------
torch.Size([3, 1, 5])
tensor([[[5, 5, 7, 1, 5]],

        [[0, 0, 9, 1, 0]],

        [[9, 9, 9, 4, 9]]])
------------------------------
torch.Size([3, 5, 1])
tensor([[[5],
         [5],
         [7],
         [1],
         [5]],

        [[0],
         [0],
         [9],
         [1],
         [0]],

        [[9],
         [9],
         [9],
         [4],
         [9]]])
------------------------------
